language: cpp
 
os:
- linux
- osx
 
env:
  matrix:
    - NODE_VERSION="10"
    - NODE_VERSION="8"
    - NODE_VERSION="6"
  include:
    - os: osx
      osx_image: xcode8.3
 
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fontconfig ; fi
- rm -rf ~/.nvm/ && git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm
- source ~/.nvm/nvm.sh
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
# Upgrade npm
# - npm install -g npm
- npm install -g node-pre-gyp 
- npm install -g node-pre-gyp-github
- git config --global credential.helper store
- git config --global github.token $NODE_PRE_GYP_GITHUB_TOKEN
- git config --global user.email "matthias.dieudonne@gmail.com"
- git config --global user.name "MatthD"

install:
# - npm install --build-from-source
- npm i nan
- node-pre-gyp configure --enable-build-type=release --enable-libopenjpeg=none --disable-libnss --disable-libtiff --disable-libpng --disable-splash-output --disable-cairo-output --disable-poppler-glib --disable-poppler-qt4 --disable-poppler-qt5 --disable-gtk-test --disable-utils --enable-cms=none --enable-dctdecoder=none --disable-zlib
- node-pre-gyp build
# - node-pre-gyp install
- node-pre-gyp package

script:
- node-pre-gyp-github publish --release

notifications:
  email: false